var DATA = {};
DATA.dates = {present:[], all:[2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011]};
DATA.locations = {present:[], all:[ 'Mumbai', 'Shanghai', 'Buenos Aires', 'Other' ]};
DATA.comments = [
{author:'Om Malik', comment:"remember this: 'to listen is to lean in, softly, with a willingness to be changed by what we hear' --Mark Nepo, poet and philosopher."},
{author:'Alejandra', comment:"Nada me motiva más a hacer ejercicio que todas las señoras en sus 30s o 40s con esos cuerpos caray!"},
{author:'DHH', comment:"Texas will waste ~$1MM to keep that poor guy in prison for 35 yrs (avg cost per inmate per year in '08 was $26K). Well spent tax money?"},
{author:'DHH', comment:"Texas man gets 35 yrs in prison for 4.6 ounces of pot: http://bit.ly/b6Hmrr - lets hope he gets out when weed is finally made legal."},
{author:'Avery Edison', comment:"I can quit making jokes about addiction any time I want."},
{author:'exuberantfool', comment:"keep calm and carry on"},
{author:'Ana Sanchez Granero', comment:"Arabic word 4 thing (shay) was transcribed as xay in Spain.Over time this was shortened to just X,symbol universally used 4 an unknow value"},
{author:'Avery Edison', comment:"Depression revealed as major cause of terrorism; TSA to start screening emotional baggage."},
{author:'Gina Trapani', comment:"RT @mathowie: 'I renamed my iPod 'The Titanic' so that when I plug it in, iTunes tells me 'The Titanic is syncing.'' http://bit.ly/cgz6kH"},
{author:'Yoshiko Sakai', comment:"como hay gente inútil en este mundo.....#pendejos"},
{author:'David Merfield', comment:"while (true==false) { giveUp(you); letDown(you); runAround(); desert(you); }"},
{author:'Avery Edison', comment:"I honestly believe that if you blended Julia Stiles with a cat, you'd get a slightly-more-human-looking Julia Stiles."},
{author:'Evan Williams', comment:"Met the Dalai Lama today in LA. Pitched him on using Twitter. He laughed."},
{author:'Simon Bostock', comment:"Today's motto: if life gives you yeast, flour, honey, salt, lukewarm water - make bread. #lemonadeschlemonade"},
{author:'Sarah Silverman', comment:"Watching @Holcombewaller in Portland. Steve plays the French horn, or as I'm still agressively sticking with, the freedom horn."},
{author:'Stephen Paul Weber', comment:"Solution to all collaboration problems: store all data as line-based text and use git. Srsly."},
{author:'Tim OReilly', comment:"Interesting: Google Gets US Approval To Buy and Sell Energy http://bit.ly/aHGsEG Very smart. Energy one of the 'raw materials' of computing"},
{author:'Alain de Botton', comment:"The office is to us what the cloister was to medieval christianity: a nominally chaste arena with an unrivalled capacity to excite desire."},
{author:'Jane McGonigal', comment:"That is true no matter what our problems, our health, our circumstances. We must try. (from 'ROGER EBERT'S LAST WORDS' in Esquire)"},
{author:'Gary Stomaun', comment:"#unsolvedmysteries If electricity comes from electrons, does morality come from morons?"},
{author:'Paula Crepaldi', comment:"#unsolvedmysteries If Barbie is so popular, then why do you have to buy her friends? Oo"},
{author:'David Pakman', comment:"From #TED Sergey Brin: 'A lot of people think I'm naive, but I wouldn't have started a search engine in 98 if I wasn't naive.' @camplejohn"},
{author:'TEDTalks Updates', comment:"'Adversity isn't an obstacle, it is our lives.' Aimee Mullins at TEDMED. http://on.ted.com/892Y"},
{author:'dougfort', comment:"RT @JPBarlow: Genius is the recovery of childhood at will. - Rimbaud"},
{author:'Patrick Collison', comment:"'A scholar is just a library's way of making another library.'—Daniel Dennett"},
{author:'Ben Casnocha', comment:"Went to Google to search 'cutting celery' -- I paused after 'cutting' and the first Google Auto-Suggest was: 'cutting yourself.'"},
{author:'Micah Baldwin', comment:"RT @ChrisKauza: “The opposite of courage in our society is not cowardice, it is conformity.” - Rollo May"},
{author:'Ben Atkin', comment:"A jQuery plugin for animated filtering and sorting: http://razorjack.net/quicksand/"},
{author:'Ben Goertzel', comment:"To our great-grandchildren: the experiential consequences of our inability to rewire our emotions at will, will be totally uncomprehended..."},
{author:'wordboner', comment:"stop bitching, start living."},
{author:'Karen McGrane', comment:"Films need directors. Orchestras need conductors. Ask 30 people to be visionary, mediocrity ensues. Hell yes, @berkun. http://bit.ly/9N0QPx"},
{author:'Alain de Botton', comment:"When we are too tired to write, that is when the interesting thoughts dare to sneak out."},
{author:'Alain de Botton', comment:"Writing opens up the otherwise unusual prospect of being violently disliked by strangers & training oneself not to mind."},
{author:'Alain de Botton', comment:"Embarking on another book, writers seldom dare note that few of their favourite authors ever wrote more than 2 or 3 works they really loved"},
{author:'Jane McGonigal', comment:"To quote the Bollywood movie 3 Idiots: 'Aal iz welll. Aal iz welll.' I have to fool my heart into not being panicked about tomorrow's talk."},
{author:'Aza Raskin', comment:"Partially. I'm running a workshop today so my time looks like a bone given to the vultures."},
{author:'Fernanda Guerra', comment:"Porque las impresoras son asi? Se ganan el odio que les tengo... Perras sarnosas"},
{author:'Ben Goertzel', comment:"An AI has just accused me of being ELIZA. This universe gets stranger every day."},
{author:'Oliver Reichenstein', comment:"'Weird how many people who know everything never do anything.' cit. @hotdogsladies"},
{author:'Adora Svitak', comment:"@flyingfingers Thanks, Mom. When you say 'What a life!' with an exclamation mark, I'm hoping you're happy, not fed up with our antics."},
{author:'Joshua Bloom', comment:"Craigslist people are retarded. I'm giving things away people, that means I'm not putting in the effort to sell it to you."},
{author:'John Hamilton', comment:"The US has 300+ million people. The other countries in the top 10 of the Index of Economic Freedom average 12 million. http://bit.ly/13Q8BP"},
{author:'Sarah Silverman', comment:"I 'ate my feelings' and I think they may have given me diarrhea."},
{author:'Alain de Botton', comment:"To try to discover what our gifts are - then to align them with something the world might need - and pay for. A lifetime's struggle."},
{author:'Mark Fletcher', comment:"I love the smell of freshly ordered servers in the morning."},
{author:'GitHub', comment:"We're about 75% back up. The bad file server is still trying to failover. Hold tight 25%ers."},
{author:'Bob Metcalfe', comment:"Last year online media was search; this year it's social. SEO/SEM has been joined by social graph optimization (SGO). #PolarisDMS"},
{author:'Sarah Silverman', comment:"Sneezing is like wet Tourette's."},
{author:'Blake Mizerany', comment:"If you don't open your mouth, is it still a yawn? -@sameerd54"},
{author:'Craig Mod', comment:"'The way you are living will have been your life.' http://tinyurl.com/y8tmgbq"},
{author:'John Perry Barlow', comment:"No one is much pleased with a companion who does not increase their fondness for themselves. - Samuel Johnson"},
{author:'Evan Williams', comment:"Overheard: 'Google versus China -- finally a fair fight!' #wef"},
{author:'Michael Cho', comment:"I can't multitask at all. My brain is basically an over-clocked 8 bit processor with a decent graphics chip."},
{author:'Sarah Silverman', comment:"Similes are like metaphors."},
{author:'Virginia Postrel', comment:"RT @chinaelitefocus: Most of econ stats from China are completely faked, but we still believe them. As Children believe in Santa Claus."},
{author:'Oliver Reichenstein', comment:"I think Obama should do Job's speeches. In return Steve does Obama's marketing."},
{author:'MarthaPC', comment:"Nestle Toll House, you can kiss my ass!! Perfect chocolate chip cookie challenge: CHECK"},
{author:'Sarah Silverman', comment:"You never hear the success stories involving autoerotic asphyxiation. #unsungheroes"},
{author:'Tom Henderson', comment:"@avantgame I want a place to submit bug reports on this broken reality."},
{author:'Alain de Botton', comment:"Relic of a religious mindset: the belief, after suffering, that we are now 'due some good news'."},
{author:'Tim OReilly', comment:"LOL: 'The meek shall inherit the earth, but not the mineral rights.' - JP Getty (via John Perry Barlow)"},
{author:'Alain de Botton', comment:"The best way to start a conversation at dinner: “So what was everyone frightened of today?”"},
{author:'Alain de Botton', comment:"It is now only the very religious who take sex seriously."},
{author:'John Perry Barlow', comment:"I'm at EG in Monterey. It's lovely. Dinner with the Minskys and Hillises. I'm smarter for the experience."},
{author:'Jeffrey Veen', comment:"Reminding myself that there is no bad or good weather, only different gear requirements."},
{author:'mike dougherty', comment:"daaaaaamn brooklyn bowl has the most annoying email blasts. this unsubscribe is gonna feel good, i can tell"},
{author:'mike dougherty', comment:"realized i've been washing dishes with 'non-ultra' joy. they should just call it 'guilt trip joy for cheapskates'"},
{author:'Caterina', comment:"OH: Tablecloths are the cufflinks of restaurants."},
{author:'Sarah Silverman', comment:"It sounds like a crude joke to say I exploded from my father's balls &out his penis hole, but it's true. Amazing to think I was so thin.."},
{author:'Sarah Silverman', comment:"I would eat fish but I can't because I have a nose."},
{author:'All Seeing AI ', comment:"once AI progresses a bit further, AIs and animals will be seen as amplifiers of ambient cosmic intelligence, not generators of intelligence"},
{author:'Sarah Silverman', comment:"What if when men got turned on their BALLS got engorged with blood& their penis got all tight& close to their bodies? That'd be WEIRD!"},
{author:'Simon Bostock', comment:"Good news, everyone! I'm the tallest person on this train! (Bad news: I'm the fattest too, with the shortest life expectancy.) #Japan"},
{author:'Marcel Molina', comment:"The value of exceptional people might not be the things they are exceptional at but that they inspire others to be exceptional as well."},
{author:'Alain de Botton', comment:"A quick way to judge character: imagine how much you'd like to be a given person's child"},
{author:'Chris Gaunt', comment:"Got the meal I asked for (おやこどん). Japanese skill +1 http://flic.kr/p/7noXxa"},
{author:'jtnix', comment:"Wrote an update for TV/Movie Cast Compare App by @jeresig. Better results for Acting Cast Members only for two shows: http://bit.ly/6RgTuX"},
{author:'Kim Ahlström', comment:"Lords of bacon, release me from this hangover with your bountiful flavour, superior fat and all-knowing wisdom."},
{author:'Aza Raskin', comment:"Woah! Just arrived in my inbox: If you ever happen to be in Boston, Stephen Wolfram would be happy to arrange to meet with you."},
{author:'Simon Bostock', comment:"Christmas in Tokyo is like Halloween in Britain - a weird, half-arsed travesty of the real thing."},
{author:'Oliver Reichenstein', comment:"Simple is... When someone or something takes care of the details."},
{author:'Joe Hewitt', comment:"If it's wrong to love Christmas music, I don't want to be right."},
{author:'MarthaPC', comment:"Just found out that in the inside of my jeans' zipper its written LUCKY YOU! Haha"},
{author:'Simon Bostock', comment:"Ok. Nobody knows where Sakuradai is. So (a) it's miles away (b) they're idiots (c) I got the name wrong. Anyway, it's a trifecta of fuckery."},
{author:'Simon Bostock', comment:"Whoops. Gone out for melon bread. Now I'm lost in a city with no street names. #savethegaijin"},
{author:'Simon Bostock', comment:"Airline food covers the three main food groups: dehydrants, diuretics and discombobulants."},
{author:'Simon Bostock', comment:"Out of here. Tokyo, baby. Going to teach the kids how much fun it is to run on travelators."},
{author:'Tim OReilly', comment:"RT @quotme: 'In the end, innovations tend to come from small groups, not from large structured efforts' - Tim OReilly/@timoreilly"},
{author:'Jonathan', comment:"Heading out into the wild for supplies. WHAT!? NO. NOT WAL-MART. Although, if meat becomes scarce, their clientele may prove quite useful."},
{author:'Jonathan', comment:"I'll make you a deal. I will stop expressing my disinterest in what you have to say if you stop talking to me."},
{author:'Erik F. Kastner', comment:"performance: 9 women can't make 1 baby in 1 month. scalability: 9 women CAN make 9 babies in 9 months"},
{author:'Jonathan', comment:"A friend asked me how old I thought she was. I answered vaguely to be safe, saying 'Young enough for acne but old enough for sagging boobs.'"},
{author:'Jonathan', comment:"I think it's adorable how my wife pauses a conversation to brush her teeth, as though I could understand what she was talking about already."},
{author:'Aza Raskin', comment:"The population of China will shortly be 1/80th of the number of people who have ever lived. http://bit.ly/5yVCM0"},
{author:'Chris Sacca', comment:"You know those people who collect every single one of the National Geographic magazines? They have issues."},
{author:'Alain de Botton', comment:"The modern state - always keener on building prisons than preventing the need for them."},
{author:'Jonathan', comment:"If you think writing in the proper tense is difficult now, just wait until time travel was possible."},
{author:'Tim OReilly', comment:"To all the folks retweeting my talk from #w2e 'Do what you do best, and link to the rest.' It's a quote from @jeffjarvis."},
{author:'Alain de Botton', comment:"Only if we had believed that God once existed would the recognition of God's non-existence mean that now anything might now be possible."},
{author:'Doug Bowman', comment:"OH: 'Someone left a crusty dried-up bowl of Corn Flakes by this desk.' Response from a row over: 'That could be anyone named Britt.'"},
{author:'Tim OReilly', comment:"And speaking of i-popping (clever pun there, @RachelCmrn), $AAPL's market cap closing in on $MSFT. http://bit.ly/2wlQz"},
{author:'Chris Pirillo', comment:"The funny from @JimGaffigan is non-stop. I think he just made my browser pee a little."},
{author:'Tiago Henriques', comment:"'one of the primary reasons that Google can write and open-source so much software is that it isn't a software company': http://tr.im/EDVQ"},
{author:'Thomas Fuchs', comment:"@jeresig it's so dead that i get a 404 on that link :)"},
{author:'Ben Casnocha', comment:"'Reading is the inhale, writing is the exhale.' - Justine Musk (whose blog is indispensable for anyone interested in writing)"},
{author:'David Pakman', comment:"Wow. But so does $MSFT. RT @pkedrosky: $AAPL has enough cash to buy 418 of the S&P 500 companies at a 20% premium. (@Dasan)"},
{author:'Marcel Molina', comment:"'There is a danger overpraising Twitter at the expense of the words it amplifies—in essence, extolling the chisel rather than Michelangelo.'"},
{author:'Marcel Molina', comment:"What first looked like two pretty girls was in fact one pretty girl and her total hippie of a boyfriend."},
{author:'yongfook', comment:"I'm sick of reading 'failure is good' articles. Stop overanalyzing your lameness and go try harder."},
{author:'Justin', comment:"'It's not the gardener's job to pick up the dog shit. If you don't want to pick up the dog shit, then learn a skill like gardening.'"},
{author:'Justin', comment:"'No, you can not borrow my t-shirt...How about instead of standing there looking shocked, you do your fucking laundry?'"},
{author:'Justin', comment:"I think the baby shit....Well, I'm smelling shit right now, so if it ain't the baby, one of you has a big fucking problem.'"},
{author:'Justin', comment:"'Fucking Radio Shack. It's a wonder they even know how to use a bathroom and don't just walk around all day with shit in their pants.'"},
{author:'Simon Bostock', comment:"Still slightly confused at the abject failure of random commuters to approach me and ask where I bought my Obama on unicorn T-shirt."},
{author:'Justin', comment:"'Here's a strawberry, sorry for farting near you...Hey! Either take the strawberry and stop bitching, or no strawberry, that's the deal.'"},
{author:'Howard Rheingold', comment:"'The first responsibility of a leader is to define reality. ' Max Depree. Obama failed in health care debate. Republicans defined reality"},
{author:'Simon Bostock', comment:"Japanese natto is uniquely evil. Rancid taste, repulsive smell, slimy texture, conceptually warped. For my kids it's like crack, though."},
{author:'Doug Bowman', comment:"One of us is happy to be at the park this morning. http://yfrog.com/0y4vufj"},
{author:'Marcos Cuevas', comment:"Lo que hace este tio con la bici que baje dios y lo vea: http://www.layers.com/david/1469"},
{author:'Justin', comment:"'It's just a fucking june bug, calm down. Jesus Christ, what happens when something bigger than a testicle attacks you?'"},
{author:'Simon Bostock', comment:"RT @fncll: I heart MeFi- it's slashdot for people who read books w/out equations, boing^2 w/out the coolkid smell http://bit.ly/jdWFM >Yep^2"},
{author:'Oliver Reichenstein', comment:"'Advertising is the tax you pay for being unremarkable.' -Robert Stephens, founder of Geek Squad (via @tferriss) (via @plasticmind)"},
{author:'Simon Bostock', comment:"Directions: it's a whole lot more enjoyable to give them than to have to listen to them."},
{author:'Paulina Parra', comment:"The night is a very dark time for me"},
{author:'Tim OReilly', comment:"#Ignite Show: Jeff Veen on Great Designers http://bit.ly/aA7J0 ' why iPhone imitators are the cargo cults of the digital era'"},
{author:'MarthaPC', comment:"What the fuck is this doctor talking about?? Nos está haciendo el super favor de exponer MUY floridamente su postura política"},
{author:'Emily', comment:"I wanted my mouth to taste like coffee, so I put some in it."},
{author:'patrissimo', comment:"Made some little parts to help me make some big ones. http://twitgoo.com/2p4aq"},
{author:'John Resig', comment:"PayPal search is the worst thing in the world. It'd be faster to ride a burro to find the person to pay in cash."},
{author:'yongfook', comment:"Time for band practice. We have been classically trained to rock your freakin socks off."},
{author:'Aza Raskin', comment:"Analogy in search of a use: It's like playing footsie with a bear trap."},
{author:'Carolina Rosas', comment:"Como respeto a mis amigos que pueden agarrar la peda desde el jueves. Los amo! Algún día me uniré al club!"},
{author:'Tetuan Valley', comment:"RT @okurispaces Trabajando para la inaguración del nuevo @OkuriSpaces en Pinos Baja (@TetuanValley) el 23 de septiembre"},
{author:'MarthaPC', comment:"A surgeon, friend of mine 'que la gente no se entere, pero a mi me gusta tanto operar, que hasta lo haria gratis'"},
{author:'Bob Metcalfe', comment:"Pondering big issues: Oh, I see, ya'll want 'PRIVACY' for you and 'TRANSPARENCY' for me. So, who owns the fact that you are a deadbeat?"},
{author:'Simon Bostock', comment:"The television in my hotel room has a larger surface area than the desk. I'm blowing this out of all proportion."},
{author:'Simon Bostock', comment:"Say what you like about Macdonalds, you won't hear a bad word from me until somebody else provides a nationwide network of public toilets."},
{author:'Kim Ahlström', comment:"Exciting. One more! Come on nature!"},
{author:'patrissimo', comment:"Today's airport 'security' thought: 'What's worse than a police state? A police theater state. All the indignity, none of the security.'"},
{author:'Carolina Rosas', comment:"Now that I've seen a picture of stephanie meyer I get why her books are crap"},
{author:'Amy Hoy', comment:"nothing says 'oh yeah, i'm on a totally different continent' like amazon.de telling me an english book will take 3 months to arrive"},
{author:'Carina', comment:"threw all that biking away at the cheesecake factory."},
{author:'AndreA SantoS', comment:"adventures happen to the adventurous..."},
{author:'sara ', comment:"belly. about. to. pop."},
{author:'John Resig', comment:"A video demonstration the Fujitsu ScanSnap document scanner that I just got: http://bit.ly/pyVnt (It's pretty awesome.)"},
{author:'David Shackelford', comment:"@elzr yeah, vision makes computing way more hardcore. my friends are all 'what?' and I'm like 'yeah'"},
{author:'MarthaPC', comment:"Mam: si se hubies checado, otra cosa fuera Papi: si mi abuelita tuviera llantas .... Fuera una bicicleta"},
{author:'Jan Lehnardt', comment:"“My girlfriend is the only working implementation of a brainfuck application I know of.” — @rmehner"},
{author:'yongfook', comment:"KEEP IT DOWN. Yongfook is hungover."},
{author:'David Shackelford', comment:"the great thing about japan is that overdone concepts from the west are new again"},
{author:'Simon Bostock', comment:"Kevin Kelly's lessons of the curves http://bit.ly/wKVps reminds me of Drucker's future that has already happened. http://bit.ly/PgW9h Scary."},
{author:'jcharlesholt', comment:"God keeps testing me, but I keep passing. You know why? Because I copy off other smart kids. You know who you are, smart friends. Thanks."},
{author:'Bob Metcalfe', comment:"Singularity University: Just met 40 students poolside sunny Mountain View. SU@NASA for 3 days including Enernet@SU talk Monday evening."},
{author:'Evan Williams', comment:"Met Warren Buffet today! Told him I was from Nebraska; he said he had to check me out—a lot of people claim to be from NE just for status ;)"},
{author:'Tiago Henriques', comment:"Thanks @jneves for lending me The 4-Hour Work Week by Tim Ferriss. Can't wait to find out how I'm wasting the other 36 hours :-)"},
{author:'Simon Bostock', comment:"Paying tips is when firms outsource quality control to their customers."},
{author:'Eric', comment:"Lost my car in Palo Alto again. Thought about gps tracker then caught myself - could just write down intersection names on a piece of paper."},
{author:'Basheera Khan', comment:"Dear god. Pop songs suddenly have meaning. And not just any pop song either: http://is.gd/1p6AZ . This is bad."},
{author:'MarthaPC', comment:"'Sometimes its easier to write a prescription than to explain the pt why he doesnt need it'"},
{author:'David Shackelford', comment:"with the amount of japanese you can fit into 140 characters, do the Japanese even need email? ツイッターの140字に言える日本語で、メールはもういらないかも笑。そごいなあ。"},
{author:'James Cox', comment:"Also, my kindle is known as gutenberg."},
{author:'Tiago Henriques', comment:"Going to the gym, à la recherche du corps perdu."},
{author:'Ken Lee', comment:"How well do you know your Japanese? http://bit.ly/Pyagk"},
{author:'Carina', comment:"Activated! Out in the 'burbs, exactly what I needed. Connected like an info IV and it feels awesome. Scary."},
{author:'Simon Bostock', comment:"RT @DianaOfPortland: [People] more frequently require to be reminded than informed. - Samuel Johnson, courtesy of @brianmarick"},
{author:'Asela', comment:"need new glasses! i'm seeing everything with a 10% alpha filter"},
{author:'Kim Ahlström', comment:"Kim: Hey, I feel like going for a jog. Nature: Oh no you don't! <rain>"},
{author:'exuberantfool', comment:"To keep my real and real-life avatars separate, I used my name for fbook URL . My 'real life self' is distinct from 'my real online self'."},
{author:'Oliver Reichenstein', comment:"The astounding world of the present future http://bit.ly/zenvQ"},
{author:'Doug Bowman', comment:"I can always tell I'm getting close to San Francisco when 3G gets replaced by Edge."},
{author:'Tiago Henriques', comment:"Finally leaving the Russian embassy. Should be angry at all the wasted time, instead I feel like I won the olympics or something."},
{author:'Basheera Khan', comment:"Dear people who think having no human details on your company's site makes you look cool and intriguing - it doesn't. Out of touch much?"},
{author:'SIME Blog', comment:"Entrepreneurship is a war story. There will be blood and there might be victory @ML #SIME"},
{author:'Basheera Khan', comment:"Never met him, but based on his handling of the #media140 audio FAIL, I'd say @moeed is funny, humble and memed to the nines."},
{author:'Amy Hoy', comment:"'Do not form business partnerships around a good idea. Form business partnerships around a good relationship.' (via @tonybgoode)"},
{author:'Thomas Fuchs', comment:"140 characters ought to be enough for anybody!"},
{author:'David Shackelford', comment:"Econ prof: 'When I was in grad school I studied too hard and got some brain damage. I was very, very smart.'"},
{author:'David Shackelford', comment:"As a conversation between geeks continues, the probability of comparing twitter clients approaches 1 #tbarcamp"},
{author:'Basheera Khan', comment:"Argh. argh. argh. Apologies, next tweet will be informative, witty, funny, or otherwise enriching. This one is all about the ARGH."},
{author:'Basheera Khan', comment:"@jasonbees You've got to hope that they're virtual machines, at the very least..."},
{author:'David Shackelford', comment:"@JAMEST0WN puns are my favorite part of this disease. #porkacolypse"},
{author:'Tiago Henriques', comment:"'back in the 90's I taught C++ & Advanced C++ to this group. I've come back tonite to apologize for having done that to u' http://tr.im/kjUX"},
{author:'Tiago Henriques', comment:"Handy OS X shortcut: Shift-Ctrl-Eject turns your monitor off if you want to leave the computer running with no image (via @mca)"},
{author:'MarthaPC', comment:"En el parque morelos, todos menos Chepe pedimos coco con guayaba, ella pidió de ciruela y mi mamá dice: char hubiera pedido de chupirul"},
{author:'exuberantfool', comment:"more inspiration for time travel http://bit.ly/kpim"},
{author:'Doug Bowman', comment:"Apparently I've never seen chrome-plated testicles dangling from the back of a truck. Is this common in Texas? http://twitpic.com/3257z"},
{author:'yongfook', comment:"Two grande-sized ice coffees later, I am freaking WIRED man. WHO WANTS TO ARM WRESTLE."},
{author:'Jeffrey Veen', comment:"Bono on who pays for music these days: 'teenage girls and very, very honest people.'"},
{author:'Joshua Bloom', comment:"#sxsw sterling: old people are dying on the vine. Put em online and make em the backbone of the new social web."},
{author:'RobinReborn', comment:"what tests could you perform on cultures to determine how they will use a technology?"},
{author:'RobinReborn', comment:"abstractions exist within abstractions, how do we know that we're not just abstractions?"},
{author:'MarthaPC', comment:"ME: bueno, luego hablamos mami MAMA: no problems, Good noches ME: ROFL"},
{author:'Eli Parra', comment:"The unreal seems impossible. Until it becomes real. The real seems inevitable. Until it becomes unreal."},
{author:'Tiago Henriques', comment:"Scandinavia: “a society — a markedly irreligious society — that was, above all, moral, stable, humane and deeply good.” http://is.gd/lvc5"},
{author:'Tiago Henriques', comment:"'Being really good at C++ is like being really good at using rocks to sharpen sticks.' More anti-C++ wit here: http://is.gd/lv8V"},
{author:'MarthaPC', comment:"Hoy verdaderamente hubo un despapaye en la carretera, un camión cargado de papaya se volcó!"},
{author:'Eli Parra', comment:"There's the Past, the Present, and the Future. And then there's the Could."},
{author:'Kim Ahlström', comment:"After empirical testing I can now confirm that a cupholder without a cup does not retain any liquid poured in it"},
{author:'RobinReborn', comment:"how do we know what we don't want ourselves to know"},
{author:'Philip Flip Kromer', comment:"Am I having fun tonight with the please refrain from depressing your mouse button here phenomenon? Yes, yes I am."}
]
